whitelistedClusterResources:
  - group: "karpenter.k8s.aws"
    kind: "EC2NodeClass"
  - group: "karpenter.sh"
    kind: "NodePool"
  - group: "storage.k8s.io"
    kind: "StorageClass"

blacklistedClusterResources: []

whitelistedNamespacedResources:
  - group: ""
    kind: "ConfigMap"
  - group: ""
    kind: "PersistentVolumeClaim"
  - group: ""
    kind: "Pod"
  - group: ""
    kind: "Secret"
  - group: ""
    kind: "Service"
  - group: ""
    kind: "Endpoint"
  - group: ""
    kind: "ServiceAccount"
  - group: "apps"
    kind: "Deployment"
  - group: "apps"
    kind: "ReplicaSet"
  - group: "apps"
    kind: "StatefulSet"
  - group: "autoscaling"
    kind: "HorizontalPodAutoscaler"
  - group: "batch"
    kind: "CronJob"
  - group: "batch"
    kind: "Job"
  - group: "bitnami.com"
    kind: "SealedSecret"
  - group: "cert-manager.io"
    kind: "Certificate"
  - group: "discovery.k8s.io"
    kind: "EndpointSlice"
  - group: "networking.k8s.io"
    kind: "Ingress"
  - group: "opentelemetry.io"
    kind: "Instrumentation"
  - group: "opentelemetry.io"
    kind: "OpenTelemetryCollector"
  - group: "policy"
    kind: "PodDisruptionBudget"
  - group: "rbac.authorization.k8s.io"
    kind: "Role"
  - group: "rbac.authorization.k8s.io"
    kind: "RoleBinding"
  - group: "secrets-store.csi.x-k8s.io"
    kind: "SecretProviderClass"
  - group: "autoscaling.k8s.io"
    kind: "VerticalPodAutoscaler"
  - group: "external-secrets.io"
    kind: "SecretStore"
  - group: "external-secrets.io"
    kind: "ExternalSecret"
  - group: "external-secrets.io"
    kind: "PushSecret"
  - group: "traefik.io"
    kind: "Middleware"

blacklistedNamespacedResources:
  - group: ""
    kind: "LimitRange"
  - group: "networking.k8s.io"
    kind: "NetworkPolicy"
  - group: ""
    kind: "ResourceQuota"

syncWindows: []
